Todo List project
Emmanuelaaron/todoList pull request #3
Opened 2021-05-04 08:00 UTC by Emmanuelaaron

2021-05-07 21:56 UTC, whiz25 requested changes
## Changes Required ✅ ✅ ✅ 
Nice work on this project. You made quite progress.
### Highlights 👍🏿 👍🏿 👍🏿 
- A user can create a new project, todo item
- A user can edit a todo
- A user can delete a todo

### Changes to make 🌵 🌵 🌵 
- Make changes to the `package.json` file. Check my comments.
- Use ES6 syntax to declare functions. Check comments


### Martin Afani
#### Slack: whiz25

2021-05-07 21:56 UTC, whiz25 commented on src/functions/project.js
> +function Project(name) {
- Use ES6 arrow function syntax

2021-05-07 21:56 UTC, whiz25 commented on src/functions/project.js
> +function Todo(name, description, dueDate, priority) {
- Replace with ES6 arrow function syntax

2021-05-07 21:56 UTC, whiz25 commented on package.json
> +  },
- Update the `scripts` with:
```json
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2021-05-10 18:59 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @Emmanuelaaron :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-05-11 04:22 UTC, merged